### ISSUE TITLE
CoAP over ENC28J60

### ISSUE THREAD

**Issue by mardecker** [przemobe/micropy-ENC28J60#5]
Is it possible to use a common CoAP library like microcoapy with your ENC28J60 Driver?

**Comment by przemobe** [comment]
Hello,
I have no experience with CoAP. However I have made quick research of https://github.com/insighio/microCoAPy and it seems to be possible to use it with the driver. 
It requires custom socket implementation.
The library probably was not tested on RP2040 so it may turn out that it will requires to solve porting issues.

Nevertheless, I am optimistic.

**Comment by przemobe** [comment]
After doing some tests, I will add an example of using [microCoAPy](https://github.com/insighio/microCoAPy) soon.

**Comment by przemobe** [comment]
Hello @mardecker,

Please check sample code: [examples/MicrocoapyClient.py](https://github.com/przemobe/micropy-ENC28J60/blob/main/examples/MicrocoapyClient.py)
CoAP library requires single modification only. Please refer to: https://github.com/insighio/microCoAPy/pull/12/files

Best regards.

**Comment by mardecker** [comment]
Thank you very much for adding the example code.
Thanks to it I made it work for my usecases. 
I am going to add AES encryption, which I should be able to import from the micropython library to make it more secure.

Have a nice day!

**Comment by mardecker** [comment]
It works fine
